"use server"

import { getGeminiApiKey } from "./settings"

interface GenerateArticleParams {
  topic: string
  category?: string
  tone?: "professional" | "casual" | "technical" | "educational"
  length?: "short" | "medium" | "long"
}

export async function generateArticleWithAI(params: GenerateArticleParams) {
  try {
    console.log("[v0] Generating article with Gemini AI:", params)

    const apiKeyResult = await getGeminiApiKey()
    if (!apiKeyResult.success || !apiKeyResult.data) {
      throw new Error("Clé API Gemini non configurée. Veuillez l'ajouter dans Paramètres > APIs > Google Gemini.")
    }
    const GEMINI_API_KEY = apiKeyResult.data

    const { topic, category = "Général", tone = "professional", length = "medium" } = params

    // Définir la longueur du contenu
    const lengthGuide = {
      short: "500-800 mots",
      medium: "1000-1500 mots",
      long: "2000-3000 mots",
    }

    // Prompt pour générer l'article
    const prompt = `Tu es un expert en rédaction d'articles de blog professionnels. Génère un article complet sur le sujet suivant:

Sujet: ${topic}
Catégorie: ${category}
Ton: ${tone}
Longueur: ${lengthGuide[length]}

L'article doit inclure:
1. Un titre accrocheur et optimisé SEO
2. Un résumé/extrait de 150-200 caractères
3. Un contenu structuré avec des sections claires (utilise le format Markdown avec ##, ###, etc.)
4. Des paragraphes bien espacés et faciles à lire
5. Des exemples concrets et pertinents
6. Une conclusion engageante
7. Un meta_title optimisé pour le SEO (60 caractères max)
8. Une meta_description optimisée pour le SEO (155 caractères max)

Réponds UNIQUEMENT avec un objet JSON valide dans ce format exact:
{
  "title": "Titre de l'article",
  "excerpt": "Résumé court de l'article",
  "content": "Contenu complet en Markdown",
  "meta_title": "Titre SEO",
  "meta_description": "Description SEO",
  "image_prompt": "Description détaillée pour générer une image de couverture professionnelle"
}`

    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${GEMINI_API_KEY}`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          contents: [
            {
              parts: [
                {
                  text: prompt,
                },
              ],
            },
          ],
          generationConfig: {
            temperature: 0.7,
            topK: 40,
            topP: 0.95,
            maxOutputTokens: 8192,
          },
        }),
      },
    )

    if (!response.ok) {
      const errorData = await response.text()
      console.error("[v0] Gemini API error:", errorData)
      throw new Error(`Gemini API error: ${response.status} - ${errorData}`)
    }

    const data = await response.json()
    console.log("[v0] Gemini API response received")

    // Extraire le texte généré
    const generatedText = data.candidates?.[0]?.content?.parts?.[0]?.text

    if (!generatedText) {
      throw new Error("No content generated by Gemini")
    }

    // Parser le JSON de la réponse
    let articleData
    try {
      // Nettoyer le texte pour extraire le JSON
      const jsonMatch = generatedText.match(/\{[\s\S]*\}/)
      if (!jsonMatch) {
        throw new Error("No JSON found in response")
      }
      articleData = JSON.parse(jsonMatch[0])
    } catch (parseError) {
      console.error("[v0] Failed to parse Gemini response:", generatedText)
      throw new Error("Failed to parse AI response")
    }

    console.log("[v0] Article generated successfully")

    // Générer l'image avec l'API Placeholder ou une vraie génération d'image
    const imageUrl = `/placeholder.svg?height=600&width=1200&query=${encodeURIComponent(articleData.image_prompt || topic)}`

    return {
      success: true,
      data: {
        title: articleData.title,
        excerpt: articleData.excerpt,
        content: articleData.content,
        meta_title: articleData.meta_title,
        meta_description: articleData.meta_description,
        featured_image_url: imageUrl,
        slug: articleData.title
          .toLowerCase()
          .normalize("NFD")
          .replace(/[\u0300-\u036f]/g, "")
          .replace(/[^a-z0-9]+/g, "-")
          .replace(/^-+|-+$/g, ""),
      },
    }
  } catch (error) {
    console.error("[v0] Error generating article with AI:", error)
    return {
      success: false,
      error: error instanceof Error ? error.message : "Failed to generate article",
    }
  }
}

// Fonction pour générer uniquement une image
export async function generateImageWithAI(prompt: string) {
  try {
    console.log("[v0] Generating image with prompt:", prompt)

    // Pour l'instant, utiliser le placeholder
    // Dans une version future, on pourrait utiliser DALL-E, Stable Diffusion, etc.
    const imageUrl = `/placeholder.svg?height=600&width=1200&query=${encodeURIComponent(prompt)}`

    return {
      success: true,
      data: { imageUrl },
    }
  } catch (error) {
    console.error("[v0] Error generating image:", error)
    return {
      success: false,
      error: error instanceof Error ? error.message : "Failed to generate image",
    }
  }
}
